<<<<<<< HEAD
# Generated by Django 4.1.7 on 2024-04-15 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_produto_creado_en'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produto',
            new_name='Producto',
        ),
    ]
=======
# Generated by Django 4.1.7 on 2024-04-15 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_produto_creado_en'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produto',
            new_name='Producto',
        ),
    ]
>>>>>>> b7cb822dfda0ffac4f10db6cf43110db479e69b3
